# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-19 09:47
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone
import django_countries.fields


class Migration(migrations.Migration):

    dependencies = [
        ('personas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='persona',
            name='pais',
            field=django_countries.fields.CountryField(default=django.utils.timezone.now, max_length=2),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='persona',
            name='telefono',
            field=models.CharField(default=0, max_length=9),
            preserve_default=False,
        ),
    ]
